import forms from '@tailwindcss/forms'

/** Industrial Sage — Material 3 tokens, ported from example/design_example/.../industrial_sage/DESIGN.md */
const m3Colors = {
  outline: '#707a6c',
  'outline-variant': '#bfcaba',
  background: '#f9f9f9',
  surface: '#f9f9f9',
  'surface-bright': '#f9f9f9',
  'surface-dim': '#dadada',
  'surface-container-lowest': '#ffffff',
  'surface-container-low': '#f3f3f3',
  'surface-container': '#eeeeee',
  'surface-container-high': '#e8e8e8',
  'surface-container-highest': '#e2e2e2',
  'surface-variant': '#e2e2e2',
  'surface-tint': '#1b6d24',
  'on-surface': '#1a1c1c',
  'on-surface-variant': '#40493d',
  'inverse-surface': '#2f3131',
  'inverse-on-surface': '#f1f1f1',
  'inverse-primary': '#88d982',
  'on-background': '#1a1c1c',
  primary: '#0d631b',
  'on-primary': '#ffffff',
  'primary-container': '#2e7d32',
  'on-primary-container': '#cbffc2',
  'primary-fixed': '#a3f69c',
  'primary-fixed-dim': '#88d982',
  'on-primary-fixed': '#002204',
  'on-primary-fixed-variant': '#005312',
  secondary: '#286b33',
  'on-secondary': '#ffffff',
  'secondary-container': '#abf4ac',
  'on-secondary-container': '#2e7238',
  'secondary-fixed': '#abf4ac',
  'secondary-fixed-dim': '#90d792',
  'on-secondary-fixed': '#002107',
  'on-secondary-fixed-variant': '#07521d',
  tertiary: '#4d5950',
  'on-tertiary': '#ffffff',
  'tertiary-container': '#657167',
  'on-tertiary-container': '#e8f5e9',
  'tertiary-fixed': '#d9e6da',
  'tertiary-fixed-dim': '#bdcabe',
  'on-tertiary-fixed': '#131e17',
  'on-tertiary-fixed-variant': '#3e4a41',
  error: '#ba1a1a',
  'on-error': '#ffffff',
  'error-container': '#ffdad6',
  'on-error-container': '#93000a',
}

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: m3Colors,
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        gutter: '16px',
        lg: '24px',
        margin: '24px',
        xl: '32px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        h1: ['Inter'],
        h2: ['Inter'],
        h3: ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'label-sm': ['Inter'],
        code: ['Inter'],
      },
      fontSize: {
        h1: ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        h2: ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['20px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        code: ['13px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
      },
    },
  },
  plugins: [forms],
}
